<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir)).'/api';

return array(
    'Slim' => array($vendorDir . '/slim/slim'),
    'Sinner\\Phpseclib' => array($vendorDir . '/sinner/phpseclib-bundle/lib'),
    'PHPExcelReader' => array($vendorDir . '/php-excel-reader/spreadsheet-reader/src'),
);
